### ISSUE TITLE
dddd

### ISSUE THREAD

**Issue by daimingchun** [sindresorhus/css-in-readme-like-wat#1]
![image](https://user-images.githubusercontent.com/6309807/88170742-c3a45c00-cc50-11ea-97bb-307fa118bfbb.png)

**Comment by ZiQiLN** [comment]
Did your cat sit on your Keyboard or something?

**Comment by sindresorhus** [comment]
edjf vgdffggcccxxxxxxddddddddddddddsssdsss

**Comment by dephraiim** [comment]
sdmcnskjvnf'ldkmj dfj diofn m dko nfme  k  c wdk scj  ;smd oka cm d ask ckos d;kod s

**Comment by JerryGreen** [comment]
He's alien, go catch him! Place him into humanizator3000. Let's make a human out of this alien!

P.S. Maybe he's just very confused of this wizardry @sindresorhus made with SVG in this repo. His "sdmcnskjvnf'ldkmj" sounds exactly like my expression when I saw it first time.

**Comment by dayvista** [comment]
I would like to see this feature as well
