### ISSUE TITLE
Suggesting an alternative approach

### ISSUE THREAD

**Issue by mahozad** [sindresorhus/css-in-readme-like-wat#12]
You could also make that with SVG animations (SMIL). Your approach does not work in IE neither does the SMIL. So we could call it a tie!

An example animated SVG:

![My logo](https://raw.githubusercontent.com/mahozad/mahozad/master/logo.svg)

**Comment by sindresorhus** [comment]
Yup. I'm aware of SMIL, but it's a bit overkill for the current example. Feel free to submit a tip to the readme about SMIL.

**Comment by mahozad** [comment]
OK, no problem.
