### ISSUE TITLE
<img> isn't working...

### ISSUE THREAD

**Issue by Harpia-Vieillot** [sindresorhus/css-in-readme-like-wat#16]

**Comment by Harpia-Vieillot** [comment]
Not displaying image...

**Comment by sindresorhus** [comment]
This is not a support forum. The image is working for me and you have provided no details to debug this further.

**Comment by Harpia-Vieillot** [comment]
I was provided an image url in that tag and that image didn't display.

refrence: https://github.com/Harpia-Vieillot/Harpia-Vieillot/blob/main/image.svg

**Comment by Harpia-Vieillot** [comment]
> This is not a support forum. The image is working for me and you have provided no details to debug this further.


I provided an image url in that tag and that image didn't display.

refrence: https://github.com/Harpia-Vieillot/Harpia-Vieillot/blob/main/image.svg
