### ISSUE TITLE
Do you think this will be patched?

### ISSUE THREAD

**Issue by Samuel-Martineau** [sindresorhus/css-in-readme-like-wat#2]
I was wondering if I should use that in my profile README or if the odds are it will be patched really soon?

**Comment by meduzen** [comment]
It’s not a bug, so it won’t be patched.

**Comment by Samuel-Martineau** [comment]
Thanks !

**Comment by twe4ked** [comment]
> It’s not a bug, so it won’t be patched.

Source on that @meduzen?

**Comment by meduzen** [comment]
It’s a browsers feature. Specifically in this case: SVG [`foreignObject`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/foreignObject).

**Comment by twe4ked** [comment]
I mean, so it `<script>`, but they don't support that. It _could_ be a bug that it's not being stripped.

**Comment by meduzen** [comment]
Deciding to stop or continue allowing a browser feature is not a bug, it’s a design decision. For now, GitHub has not decided to remove support of foreignObjects in external SVGs.

Will they in the future? Maybe yes, maybe not. But it’s not and never will be a bug.
