### ISSUE TITLE
readme.svg?

### ISSUE THREAD

**Issue by fisker** [sindresorhus/css-in-readme-like-wat#4]
I think GitHub support `readme.*` as readme?

**Comment by sindresorhus** [comment]
Did you try?

**Comment by fisker** [comment]
> You found a secret! fisker/fisker is a ✨special ✨ repository that you can use to add a README.md to your GitHub profile. Make sure it’s public and initialize it with a README to get started.

It says `README.md`, but I'll try.

**Comment by fisker** [comment]
Tested. `readme.svg`/`readme.html` only showing the source code.
