### ISSUE TITLE
Can this technique also be applied to JS?

### ISSUE THREAD

**Issue by sugarfi** [sindresorhus/css-in-readme-like-wat#9]
Ok, so this isn't actually an *issue*, per se, but discussions aren't enabled and I was curious. Can this technique be used to insert script tags into a README? I assume  Github blocks these tags at the top level, but does that same behavior apply to foreignObject tags?

**Comment by lovetingyuan** [comment]
Of course you can not.

**Comment by papb** [comment]
I hope it is not possible. Otherwise that would be a major security issue.

**Comment by sindresorhus** [comment]
No, GitHub strips/blocks everything.
